name: Deploy Frontend
on:
  push:
    branches: [ "main", "master" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
        env:
          CI: false
      - name: Copy Build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 88.222.214.155
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/*"
          target: "/var/www/ssbwithisv/frontend"
          strip_components: 1
